<!DOCTYPE html>
<html>
<head>
	<title><?php
      include "/script-checker/students.php";
			$student='mrh';
			if (array_key_exists('student', $_GET)) {
				$student=$_GET['student'];
				} else {
				$student='mrh';
				}
      if (array_key_exists('alt', $_GET)) {
        $alt = 1;
      } else {
        $alt = 0;
      }
			echo $student; 
		?>'s CSS Garden</title>
	<link type='text/css' rel='stylesheet' href='<?php 
                                               if ($student == 'mrh') {
                                                 echo 'http://slabweb.tk/mrh';
                                               } elseif ($student == 'dualitypanda') {
                                                 echo 'http://pandathernation.x10host.com';
                                               } else {

                                                 echo 'http://slabweb';
                                                 if ($alt) { echo '17'; } 
                                                 echo '.phpwebhosting.com/';
                                                 echo $student;
                                               } ?>/garden.css' />
</head>
<body>

<div id='all'>
	<header>
		<h1>The Summer Lab CSS Garden</h1>
	</header>
	
  <nav>
		<h2>Choose a style:</h2>
		<ul>
	<?php
		include '../script-checker/students.php';
		for ($i=0; $i<count($students); $i++)
			{
			echo "<li><a href='?student=" . $students[$i];
			if (in_array($students[$i], $alternates)) {
				echo "&alt=1";
			}
			echo "'>" . $students[$i] . "</a></li>";
			}
		?>
		</ul>
	</nav>
  
	<main>
		<h2>Lorem Ipsum</h2>
		
		<section>
			<h3>Dolor Sit Amat</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In iaculis porta massa vitae laoreet. Duis tristique turpis hendrerit sapien tempor vitae ultrices eros lobortis. Suspendisse et tristique lectus. Nulla pulvinar, neque nec congue eleifend, dui magna congue mauris, ac tincidunt est ipsum ac elit. Nunc dignissim, nisi a venenatis commodo, ante risus adipiscing neque, eget vestibulum orci dui malesuada nibh. In eleifend nisl sed tortor venenatis aliquet. Quisque aliquam fringilla eros, eget mattis tellus dictum at. Maecenas id eros id lectus pellentesque tempor vel in nulla. Praesent vitae turpis sit amet tellus vulputate scelerisque et sit amet tortor. Maecenas dapibus viverra ornare.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse laoreet suscipit tortor, id suscipit neque tristique nec. Nam ultricies, nisi dignissim tempus interdum, massa quam imperdiet dolor, adipiscing viverra tellus magna placerat quam. Vivamus rhoncus dignissim enim. Integer ut lorem libero, aliquet accumsan tortor. In sit amet pulvinar leo. Nulla porta dui justo. Aliquam vel purus massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisl sem, varius tristique adipiscing a, interdum nec orci. Nunc id leo nibh, sit amet elementum dolor. Integer vitae ipsum dui. Integer lectus nisi, cursus non pretium id, feugiat nec nisl. Nunc rutrum feugiat bibendum. Suspendisse sed fringilla enim.</p>
		</section>
		
		<section>
			<h3>Consequitur</h3>
			<p>Bacon ipsum dolor sit amet capicola strip steak speck, turducken ex bresaola id.  Qui sunt ground round corned beef quis sint nulla venison laboris.  Aute drumstick qui, pork chop in hamburger consectetur t-bone jowl mollit esse.  Swine aliqua qui beef ribs meatball, turkey tenderloin aliquip cillum.</p>
			<p>Ex officia tenderloin, et aliquip enim short loin dolore corned beef pariatur andouille eu pork prosciutto.  Rump reprehenderit shoulder voluptate exercitation, tri-tip shank.  Fatback labore capicola dolore non chuck t-bone.  Meatball tenderloin jowl short loin, sunt tri-tip pastrami labore short ribs speck ball tip dolore.  Pancetta leberkas nostrud ground round, ex ad tongue eiusmod culpa andouille.  Aliqua speck drumstick velit, veniam venison shoulder irure flank.  T-bone beef ribs duis, commodo nostrud shank minim adipisicing.</p>

		</section>
	</main>
	
	<footer>
		<h2>This is a footer.</h2>
		<p>Text generated by Mr. H, <a href='http://lipsum.com'>Lipsum.com</a>, and <a href='http://baconipsum.com'>BaconIpsum.com</a> .</p>
	</footer>
	
</div>

</body>
</html>